//Victor Hugo Concolato Neves - 2576139

import java.time.format.DateTimeFormatter;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author conco
 */
public class FormConVenda extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormConVenda.class.getName());
    private DefaultTableModel modTab;
    private Venda v;
    private BdMovel bdMovel = BdMovel.getInstance();
    private BdPessoa bdPessoa = BdPessoa.getInstance();
    private BdVenda bdVenda = BdVenda.getInstance();

    //Inicio MÉTODO SINGLETON
    private static FormConVenda conVendaInstance;
    
    private FormConVenda() {
        initComponents();
    }
    
    public static FormConVenda getInstance(){
        if(conVendaInstance==null){
            conVendaInstance = new FormConVenda();
        }
        return conVendaInstance;
    }
    //Fim MÉTODO SINGLETON

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtTitulo = new javax.swing.JLabel();
        rtId = new javax.swing.JLabel();
        cxId = new javax.swing.JFormattedTextField();
        btProcurar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        panConVenda = new javax.swing.JPanel();
        rtData = new javax.swing.JLabel();
        cxData = new javax.swing.JFormattedTextField();
        rtValorTotalVenda = new javax.swing.JLabel();
        cxValorTotalVenda = new javax.swing.JFormattedTextField();
        panCorrigeBug = new javax.swing.JPanel();
        rtVendedor = new javax.swing.JLabel();
        cxVendedor = new javax.swing.JFormattedTextField();
        rtCliente = new javax.swing.JLabel();
        cxCliente = new javax.swing.JFormattedTextField();
        rtNomeVendedor = new javax.swing.JLabel();
        rtNomeCliente = new javax.swing.JLabel();
        rtNomeMovel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMovel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        rtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rtTitulo.setText("Consulta de Vendas");

        rtId.setText("ID:");

        cxId.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        btProcurar.setText("🔍");
        btProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProcurarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        rtData.setText("Data:");

        cxData.setEditable(false);
        try {
            cxData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cxData.setEnabled(false);

        rtValorTotalVenda.setText("Valor Total");

        cxValorTotalVenda.setEditable(false);
        cxValorTotalVenda.setEnabled(false);

        rtVendedor.setText("Vendedor (ID):");

        cxVendedor.setEditable(false);
        cxVendedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        cxVendedor.setEnabled(false);
        cxVendedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cxVendedorFocusLost(evt);
            }
        });

        rtCliente.setText("Cliente (ID):");

        cxCliente.setEditable(false);
        cxCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        cxCliente.setEnabled(false);
        cxCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cxClienteFocusLost(evt);
            }
        });

        javax.swing.GroupLayout panCorrigeBugLayout = new javax.swing.GroupLayout(panCorrigeBug);
        panCorrigeBug.setLayout(panCorrigeBugLayout);
        panCorrigeBugLayout.setHorizontalGroup(
            panCorrigeBugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCorrigeBugLayout.createSequentialGroup()
                .addGroup(panCorrigeBugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtVendedor)
                    .addComponent(rtCliente))
                .addGap(39, 39, 39)
                .addGroup(panCorrigeBugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panCorrigeBugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtNomeMovel)
                    .addComponent(rtNomeCliente)
                    .addComponent(rtNomeVendedor))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        panCorrigeBugLayout.setVerticalGroup(
            panCorrigeBugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCorrigeBugLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panCorrigeBugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtVendedor)
                    .addComponent(cxVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtNomeVendedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panCorrigeBugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtCliente)
                    .addComponent(rtNomeCliente))
                .addGap(193, 193, 193)
                .addComponent(rtNomeMovel))
        );

        tbMovel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Móvel", "Quantidade", "Valor Un", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbMovel.setEnabled(false);
        jScrollPane1.setViewportView(tbMovel);

        javax.swing.GroupLayout panConVendaLayout = new javax.swing.GroupLayout(panConVenda);
        panConVenda.setLayout(panConVendaLayout);
        panConVendaLayout.setHorizontalGroup(
            panConVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConVendaLayout.createSequentialGroup()
                .addComponent(rtData, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(cxData, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(panCorrigeBug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panConVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(panConVendaLayout.createSequentialGroup()
                    .addComponent(rtValorTotalVenda)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cxValorTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panConVendaLayout.setVerticalGroup(
            panConVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConVendaLayout.createSequentialGroup()
                .addGroup(panConVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtData)
                    .addComponent(cxData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(panCorrigeBug, javax.swing.GroupLayout.PREFERRED_SIZE, 93, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panConVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtValorTotalVenda)
                    .addComponent(cxValorTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtId)
                                .addGap(18, 18, 18)
                                .addComponent(cxId, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btProcurar))
                            .addComponent(panConVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(btExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(rtTitulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rtTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtId)
                    .addComponent(btProcurar))
                .addGap(18, 18, 18)
                .addComponent(panConVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btExcluir)
                    .addComponent(btSair))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cxVendedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cxVendedorFocusLost
        nomePessoa(false);
    }//GEN-LAST:event_cxVendedorFocusLost

    private void cxClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cxClienteFocusLost
        nomePessoa(true);
    }//GEN-LAST:event_cxClienteFocusLost

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        try {
            excluir();
        } catch (ValorNumericoInvalidoException ex) {
            System.getLogger(FormConVenda.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProcurarActionPerformed
        procurar();
    }//GEN-LAST:event_btProcurarActionPerformed

    public JFormattedTextField getCxId() {
        return cxId;
    }
    
    private void excluir() throws ValorNumericoInvalidoException{
        int escolha = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir esta venda permanentemente? Esta ação não poderá ser desfeita.", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if(escolha==0){
            bdVenda.rmvVenda(v.getId());
            atualizarTabelaRelatorio();
            limparForm();
            hideForm();
        }
    }
    
    private void atualizarTabelaRelatorio(){
        FormRelVenda.getInstance().valoresTabela();
    }    
    
    public void procurar(){
        if(cxId.getValue()!=null){
            v = bdVenda.getVenda(((Number) cxId.getValue()).intValue());
            if(v!=null){
                if(panConVenda.isVisible()){
                    hideForm();
                }
                hideForm();
                Object id = cxId.getValue();
                limparForm();
                cxId.setValue(id);
                valores();
            }else{
               JOptionPane.showMessageDialog(null, "O ID inserido é inválido. Por favor, verifique e tente novamente", "Erro de Validação de ID", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Para realizar a pesquisa, é necessário inserir um ID no campo correspondente. Por favor, preencha o campo ID e tente novamente.", "Campo ID Vazio", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void valores(){
        cxData.setValue(v.getData().format(DateTimeFormatter.ofPattern("dd/MM/uuuu")));
        cxVendedor.setValue(v.getVendedor().getId());
        rtNomeVendedor.setText(v.getVendedor().getNome());
        cxCliente.setValue(v.getCliente().getId());
        rtNomeCliente.setText(v.getCliente().getNome());
        for (ItemVenda item : v.getItensVenda()) {
            //Reflexividade
            modTab.addRow(new Object[]{item.getMovel().getNome(), item.getQuantidade(), item.getMovel().getValor().getValorVenda(), item.calcularValorTotal()});
        }
        cxValorTotalVenda.setValue(v.calcularValorTotal());
    }
    
    private void sair(){
        int escolha = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair da tela de consulta de vendas?", "Confirmar Saída", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if(escolha==0){
            limparForm();
            this.dispose();            
        }
    }
    
    private void limparForm(){
        cxId.setValue(null);
        cxCliente.setValue(null);
        cxData.setValue(null);
        cxId.setValue(null);
        cxValorTotalVenda.setValue(null);
        cxVendedor.setValue(null);
        rtNomeMovel.setText("");
        rtNomeCliente.setText("");
        rtNomeVendedor.setText("");
        modTab = (DefaultTableModel) tbMovel.getModel();
        modTab.setRowCount(0);
    }
    
    private void nomePessoa(boolean cliente) {
        Object valor = cliente ? cxCliente.getValue() : cxVendedor.getValue();

        if (valor != null) {
            int id = ((Number) valor).intValue();
            Pessoa p = bdPessoa.getPessoa(id);

            String nomeOuErro = (p != null) ? p.getNome() : "Id inválido!";

            if (cliente) {
                rtNomeCliente.setText(nomeOuErro);
            } else {
                rtNomeVendedor.setText(nomeOuErro);
            }
        }
    }
    
    private void hideForm(){
        boolean visible = !panConVenda.isVisible();
        panConVenda.setVisible(visible);
        btExcluir.setVisible(visible);
    }
    
    public void init(){
        this.setVisible(true);
        hideForm();
        v = new Venda();
        modTab = (DefaultTableModel) tbMovel.getModel();
    }
       
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormConVenda().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btProcurar;
    private javax.swing.JButton btSair;
    private javax.swing.JFormattedTextField cxCliente;
    private javax.swing.JFormattedTextField cxData;
    private javax.swing.JFormattedTextField cxId;
    private javax.swing.JFormattedTextField cxValorTotalVenda;
    private javax.swing.JFormattedTextField cxVendedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panConVenda;
    private javax.swing.JPanel panCorrigeBug;
    private javax.swing.JLabel rtCliente;
    private javax.swing.JLabel rtData;
    private javax.swing.JLabel rtId;
    private javax.swing.JLabel rtNomeCliente;
    private javax.swing.JLabel rtNomeMovel;
    private javax.swing.JLabel rtNomeVendedor;
    private javax.swing.JLabel rtTitulo;
    private javax.swing.JLabel rtValorTotalVenda;
    private javax.swing.JLabel rtVendedor;
    private javax.swing.JTable tbMovel;
    // End of variables declaration//GEN-END:variables
}
