//Victor Hugo Concolato Neves - 2576139

import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author conco
 */
public class FormConMovel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormConMovel.class.getName());
    private BdMovel bd = BdMovel.getInstance();
    private Movel m;
    private Valor valor;

    //Inicio MÉTODO SINGLETON
    private static FormConMovel conMovelInstance;

    private FormConMovel() {
        initComponents();
    }
    
    public static FormConMovel getInstance(){
        if(conMovelInstance==null){
            conMovelInstance = new FormConMovel();
        }
        return conMovelInstance;
    }
    //Fim MÉTODO SINGLETON

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGrupoEspelho = new javax.swing.ButtonGroup();
        btGrupoFreezer = new javax.swing.ButtonGroup();
        rtTitulo = new javax.swing.JLabel();
        rtId = new javax.swing.JLabel();
        cxId = new javax.swing.JFormattedTextField();
        btProcurar = new javax.swing.JButton();
        panConMovel = new javax.swing.JPanel();
        rtNome = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        rtQtdd = new javax.swing.JLabel();
        cxQtdd = new javax.swing.JFormattedTextField();
        rtValorCusto = new javax.swing.JLabel();
        cxValorCusto = new javax.swing.JFormattedTextField();
        rtValorVenda = new javax.swing.JLabel();
        cxValorVenda = new javax.swing.JFormattedTextField();
        rtLucro = new javax.swing.JLabel();
        cxLucro = new javax.swing.JFormattedTextField();
        panConGuardaRoupa = new javax.swing.JPanel();
        rtQtddPortasGuardaRoupa = new javax.swing.JLabel();
        cxQtddPortasGuardaRoupa = new javax.swing.JFormattedTextField();
        rtEspelhoGuardaRoupa = new javax.swing.JLabel();
        btEspelhoSim = new javax.swing.JRadioButton();
        btEspelhoNao = new javax.swing.JRadioButton();
        panConGeladeira = new javax.swing.JPanel();
        rtCapacidadeGeladeira = new javax.swing.JLabel();
        cxCapacidadeGeladeira = new javax.swing.JFormattedTextField();
        rtFreezerGeladeira = new javax.swing.JLabel();
        btFreezerSim = new javax.swing.JRadioButton();
        btFreezerNao = new javax.swing.JRadioButton();
        panConMesa = new javax.swing.JPanel();
        rtQtddLugaresMesa = new javax.swing.JLabel();
        cxQtddLugaresMesa = new javax.swing.JFormattedTextField();
        rtFormatoMesa = new javax.swing.JLabel();
        cxFormatoMesa = new javax.swing.JTextField();
        btAtualizar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        rtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rtTitulo.setText("Consulta de Móveis");

        rtId.setText("ID:");

        cxId.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        btProcurar.setText("🔍");
        btProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProcurarActionPerformed(evt);
            }
        });

        rtNome.setText("Nome:");

        rtQtdd.setText("Quantidade em estoque:");

        cxQtdd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        rtValorCusto.setText("Valor de custo:");

        cxValorCusto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        cxValorCusto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cxValorCustoFocusLost(evt);
            }
        });
        cxValorCusto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cxValorCustoKeyReleased(evt);
            }
        });

        rtValorVenda.setText("Valor de venda:");

        cxValorVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        cxValorVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cxValorVendaFocusLost(evt);
            }
        });
        cxValorVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cxValorVendaKeyReleased(evt);
            }
        });

        rtLucro.setText("Lucro:");

        cxLucro.setEditable(false);
        cxLucro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        cxLucro.setEnabled(false);

        javax.swing.GroupLayout panConMovelLayout = new javax.swing.GroupLayout(panConMovel);
        panConMovel.setLayout(panConMovelLayout);
        panConMovelLayout.setHorizontalGroup(
            panConMovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConMovelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panConMovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtQtdd)
                    .addComponent(rtValorCusto)
                    .addComponent(rtValorVenda)
                    .addComponent(rtLucro))
                .addGap(47, 47, 47)
                .addGroup(panConMovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxNome, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addGroup(panConMovelLayout.createSequentialGroup()
                        .addGroup(panConMovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cxValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cxValorCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cxQtdd, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 119, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panConMovelLayout.setVerticalGroup(
            panConMovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConMovelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panConMovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panConMovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtQtdd)
                    .addComponent(cxQtdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panConMovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtValorCusto)
                    .addComponent(cxValorCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panConMovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtValorVenda)
                    .addComponent(cxValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panConMovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtLucro)
                    .addComponent(cxLucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        rtQtddPortasGuardaRoupa.setText("Quantidade de portas:");

        cxQtddPortasGuardaRoupa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        rtEspelhoGuardaRoupa.setText("Possui espelho?");

        btGrupoEspelho.add(btEspelhoSim);
        btEspelhoSim.setText("Sim");

        btGrupoEspelho.add(btEspelhoNao);
        btEspelhoNao.setText("Não");

        javax.swing.GroupLayout panConGuardaRoupaLayout = new javax.swing.GroupLayout(panConGuardaRoupa);
        panConGuardaRoupa.setLayout(panConGuardaRoupaLayout);
        panConGuardaRoupaLayout.setHorizontalGroup(
            panConGuardaRoupaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConGuardaRoupaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panConGuardaRoupaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtEspelhoGuardaRoupa)
                    .addComponent(rtQtddPortasGuardaRoupa))
                .addGap(59, 59, 59)
                .addGroup(panConGuardaRoupaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panConGuardaRoupaLayout.createSequentialGroup()
                        .addComponent(btEspelhoSim)
                        .addGap(36, 36, 36)
                        .addComponent(btEspelhoNao))
                    .addComponent(cxQtddPortasGuardaRoupa, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );
        panConGuardaRoupaLayout.setVerticalGroup(
            panConGuardaRoupaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConGuardaRoupaLayout.createSequentialGroup()
                .addGroup(panConGuardaRoupaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtQtddPortasGuardaRoupa)
                    .addComponent(cxQtddPortasGuardaRoupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panConGuardaRoupaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtEspelhoGuardaRoupa)
                    .addComponent(btEspelhoSim)
                    .addComponent(btEspelhoNao)))
        );

        rtCapacidadeGeladeira.setText("Capacidade (Litros):");

        cxCapacidadeGeladeira.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        rtFreezerGeladeira.setText("Possui Freezer?");

        btGrupoFreezer.add(btFreezerSim);
        btFreezerSim.setText("Sim");

        btGrupoFreezer.add(btFreezerNao);
        btFreezerNao.setText("Não");

        javax.swing.GroupLayout panConGeladeiraLayout = new javax.swing.GroupLayout(panConGeladeira);
        panConGeladeira.setLayout(panConGeladeiraLayout);
        panConGeladeiraLayout.setHorizontalGroup(
            panConGeladeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panConGeladeiraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panConGeladeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtCapacidadeGeladeira)
                    .addComponent(rtFreezerGeladeira))
                .addGap(71, 71, 71)
                .addGroup(panConGeladeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxCapacidadeGeladeira, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panConGeladeiraLayout.createSequentialGroup()
                        .addComponent(btFreezerSim)
                        .addGap(36, 36, 36)
                        .addComponent(btFreezerNao)))
                .addGap(43, 43, 43))
        );
        panConGeladeiraLayout.setVerticalGroup(
            panConGeladeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConGeladeiraLayout.createSequentialGroup()
                .addGroup(panConGeladeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtCapacidadeGeladeira)
                    .addComponent(cxCapacidadeGeladeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panConGeladeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtFreezerGeladeira)
                    .addComponent(btFreezerSim)
                    .addComponent(btFreezerNao)))
        );

        rtQtddLugaresMesa.setText("Quantidade de lugares:");

        cxQtddLugaresMesa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        rtFormatoMesa.setText("Formato:");

        javax.swing.GroupLayout panConMesaLayout = new javax.swing.GroupLayout(panConMesa);
        panConMesa.setLayout(panConMesaLayout);
        panConMesaLayout.setHorizontalGroup(
            panConMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConMesaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panConMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtQtddLugaresMesa)
                    .addComponent(rtFormatoMesa))
                .addGroup(panConMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panConMesaLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(cxQtddLugaresMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panConMesaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxFormatoMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panConMesaLayout.setVerticalGroup(
            panConMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConMesaLayout.createSequentialGroup()
                .addGroup(panConMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtQtddLugaresMesa)
                    .addComponent(cxQtddLugaresMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panConMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtFormatoMesa)
                    .addComponent(cxFormatoMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtId)
                                .addGap(18, 18, 18)
                                .addComponent(cxId, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btProcurar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btAtualizar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btExcluir)
                                    .addGap(18, 18, 18)
                                    .addComponent(btSair))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panConMovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(panConMesa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(panConGuardaRoupa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(panConGeladeira, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(rtTitulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(rtTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtId)
                    .addComponent(cxId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btProcurar))
                .addGap(18, 18, 18)
                .addComponent(panConMovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panConGuardaRoupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panConGeladeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panConMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAtualizar)
                    .addComponent(btSair)
                    .addComponent(btExcluir))
                .addGap(16, 16, 16))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cxValorVendaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxValorVendaKeyReleased
        try {
            calculaLucro();
        } catch (ValorNumericoInvalidoException ex) {
            JOptionPane.showMessageDialog(null, ex.impErro(), "Erro", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_cxValorVendaKeyReleased

    private void cxValorCustoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxValorCustoKeyReleased
        try {
            calculaLucro();
        } catch (ValorNumericoInvalidoException ex) {
            JOptionPane.showMessageDialog(null, ex.impErro(), "Erro", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_cxValorCustoKeyReleased

    private void cxValorCustoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cxValorCustoFocusLost
        try {
            calculaLucro();
        } catch (ValorNumericoInvalidoException ex) {
            JOptionPane.showMessageDialog(null, ex.impErro(), "Erro", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_cxValorCustoFocusLost

    private void cxValorVendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cxValorVendaFocusLost
        try {
            calculaLucro();
        } catch (ValorNumericoInvalidoException ex) {
            JOptionPane.showMessageDialog(null, ex.impErro(), "Erro", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_cxValorVendaFocusLost

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        try {
            atualizar();
        } catch (ValorNumericoInvalidoException ex) {
            JOptionPane.showMessageDialog(null, ex.impErro(), "Erro", JOptionPane.OK_OPTION);
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        try {
            excluir();        
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProcurarActionPerformed
        try {
            procurar();
        } catch (ValorNumericoInvalidoException ex) {
            JOptionPane.showMessageDialog(null, ex.impErro(), "Erro", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_btProcurarActionPerformed

    public JFormattedTextField getCxId() {
        return cxId;
    }
    
    private void excluir(){
        int escolha = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir este móvel permanentemente? Esta ação não poderá ser desfeita.", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if(escolha==0){
            bd.rmvMovel(m.getId());
            atualizarTabelaRelatorio();
            limparForm();
            hideForm();
        }
    }
    
    private void atualizarTabelaRelatorio(){
        FormRelMovel.getInstance().valoresTabela();
    }
    
    public void procurar() throws ValorNumericoInvalidoException{
        hideForm();
        if(cxId.getValue()!=null){
            m = bd.getMovel(((Number) cxId.getValue()).intValue());
            if(m!=null){
                panConMovel.setVisible(true);
                btAtualizar.setVisible(true);
                btExcluir.setVisible(true);
                switch (m.getClass().getName()) {
                    case "Geladeira" -> {
                        panConGeladeira.setVisible(true);
                        rtTitulo.setText("Consulta de Geladeira");
                    }
                    case "Mesa" -> {
                        panConMesa.setVisible(true);
                        rtTitulo.setText("Consulta de Mesa");
                    }
                    default -> {
                        panConGuardaRoupa.setVisible(true);
                        rtTitulo.setText("Consulta de Guarda Roupa");
                    }
                }
                valores();
                calculaLucro();
            }else{
               JOptionPane.showMessageDialog(null, "O ID inserido é inválido. Por favor, verifique e tente novamente", "Erro de Validação de ID", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Para realizar a pesquisa, é necessário inserir um ID no campo correspondente. Por favor, preencha o campo ID e tente novamente.", "Campo ID Vazio", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void valores(){
        cxNome.setText(m.getNome());
        cxQtdd.setValue(m.getQuantidadeEstoque());
        //Reflexividade
        cxValorCusto.setValue(m.getValor().getValorCusto());
        //Reflexividade
        cxValorVenda.setValue(m.getValor().getValorVenda());
        switch (m.getClass().getName()) {
            case "Geladeira" -> {
                Geladeira g = (Geladeira) m;
                cxCapacidadeGeladeira.setValue(g.getCapacidadeLitros());
                if(g.isFreezer()){
                    btFreezerSim.setSelected(true);
                }else{
                    btFreezerNao.setSelected(true);
                }
            }
            case "Mesa" -> {
                Mesa mesa = (Mesa) m;
                cxQtddLugaresMesa.setValue(mesa.getQuantidadeLugares());
                cxFormatoMesa.setText(mesa.getFormato());
            }
            default -> {
                GuardaRoupa g = (GuardaRoupa) m;
                cxQtddPortasGuardaRoupa.setValue(g.getQuantidadePortas());
                if(g.isEspelho()){
                    btEspelhoSim.setSelected(true);
                }else{
                    btEspelhoNao.setSelected(true);
                }
            }
        }
    }
    
    private void atualizar() throws ValorNumericoInvalidoException{
        if(verificaPreenchimento()){
            switch (m.getClass().getName()) {
                case "Geladeira" -> {
                    Geladeira geladeira = (Geladeira) m;
                    geladeira.setCapacidadeLitros(((Number) cxCapacidadeGeladeira.getValue()).intValue());
                    geladeira.setFreezer(btFreezerSim.isSelected());
                }
                case "GuardaRoupa" -> {
                    GuardaRoupa guardaRoupa = (GuardaRoupa) m;
                    guardaRoupa.setQuantidadePortas(((Number)cxQtddPortasGuardaRoupa.getValue()).intValue());
                    guardaRoupa.setEspelho(btEspelhoSim.isSelected());
                }
                default -> {
                    Mesa mesa = (Mesa) m;
                    mesa.setFormato(cxFormatoMesa.getText());
                    mesa.setQuantidadeLugares(((Number) cxQtddLugaresMesa.getValue()).intValue());
                }
            }
            m.setNome(cxNome.getText());
            m.setQuantidadeEstoque(((Number)cxQtdd.getValue()).intValue());
            //Reflexividade
            m.getValor().setValorCusto(valor.getValorCusto());
            //Reflexividade
            m.getValor().setValorVenda(valor.getValorVenda());
            bd.attMovel(m);
            JOptionPane.showMessageDialog(
                    null,
                    "Os dados do móvel foram atualizados com sucesso\n"
                    +m.exibirInformacoes(),
                    "Atualização Concluída",
                    JOptionPane.INFORMATION_MESSAGE);
            atualizarTabelaRelatorio();
            limparForm();
            hideForm();
        }else{
            JOptionPane.showMessageDialog(null, "Todos os campos do formulário são obrigatórios. Por favor, preencha-os para continuar.", "Campos Obrigatórios", JOptionPane.OK_OPTION);
        }
    }
    
    private boolean verificaPreenchimento(){
        if(cxId.getText().isBlank() || cxNome.getText().isBlank() || cxQtdd.getText().isBlank() || cxValorCusto.getText().isBlank() || cxValorVenda.getText().isBlank()){
                return false;
            }
        switch (m.getClass().getName()) {
            case "Geladeira" -> {
                if(cxCapacidadeGeladeira.getText().isBlank() || btGrupoFreezer.getSelection()==null){
                    return false;
                }
            }
            case "Mesa" -> {
                if(cxQtddLugaresMesa.getText().isBlank() || cxFormatoMesa.getText().isBlank()){
                    return false;
                }
            }
            default -> {
                if(cxQtddPortasGuardaRoupa.getText().isBlank() || btGrupoEspelho.getSelection()==null){
                    return false;
                }
            }
        }
        return true;
    }
    
    private void sair(){
        int escolha = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair da tela de consulta de móveis?", "Confirmar Saída", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if(escolha==0){
            limparForm();
            this.dispose();            
        }
    }
    
    private void limparForm(){
        cxId.setValue(null);
        cxNome.setText("");
        cxQtdd.setValue(null);
        cxValorCusto.setValue(null);
        cxValorVenda.setValue(null);
        cxLucro.setValue(null);
        cxCapacidadeGeladeira.setValue(null);
        cxFormatoMesa.setText("");
        cxQtddLugaresMesa.setValue(null);
        cxQtddPortasGuardaRoupa.setValue(null);
        btGrupoEspelho.clearSelection();
        btGrupoFreezer.clearSelection();
        rtTitulo.setText("Consulta de Móveis");
    }
    
    private double replaceComma(String number){
        return Double.parseDouble(number.replace(".","").replace(',', '.'));
    }
    
    private void calculaLucro() throws ValorNumericoInvalidoException{
        if(!(cxValorVenda.getText().isBlank() || cxValorCusto.getText().isBlank())){
            valor.setValorCusto(replaceComma(cxValorCusto.getText()));
            valor.setValorVenda(replaceComma(cxValorVenda.getText()));            
            cxLucro.setValue(valor.getLucro());
        }else{
            cxLucro.setValue(null);
        }
    }
    
    public void init(){
        this.setVisible(true);
        valor = new Valor();
        this.hideForm();      
    }
    
    private void hideForm(){
        panConGeladeira.setVisible(false);
        panConGuardaRoupa.setVisible(false);
        panConMesa.setVisible(false);
        panConMovel.setVisible(false);
        btAtualizar.setVisible(false);
        btExcluir.setVisible(false);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormConMovel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JRadioButton btEspelhoNao;
    private javax.swing.JRadioButton btEspelhoSim;
    private javax.swing.JButton btExcluir;
    private javax.swing.JRadioButton btFreezerNao;
    private javax.swing.JRadioButton btFreezerSim;
    private javax.swing.ButtonGroup btGrupoEspelho;
    private javax.swing.ButtonGroup btGrupoFreezer;
    private javax.swing.JButton btProcurar;
    private javax.swing.JButton btSair;
    private javax.swing.JFormattedTextField cxCapacidadeGeladeira;
    private javax.swing.JTextField cxFormatoMesa;
    private javax.swing.JFormattedTextField cxId;
    private javax.swing.JFormattedTextField cxLucro;
    private javax.swing.JTextField cxNome;
    private javax.swing.JFormattedTextField cxQtdd;
    private javax.swing.JFormattedTextField cxQtddLugaresMesa;
    private javax.swing.JFormattedTextField cxQtddPortasGuardaRoupa;
    private javax.swing.JFormattedTextField cxValorCusto;
    private javax.swing.JFormattedTextField cxValorVenda;
    private javax.swing.JPanel panConGeladeira;
    private javax.swing.JPanel panConGuardaRoupa;
    private javax.swing.JPanel panConMesa;
    private javax.swing.JPanel panConMovel;
    private javax.swing.JLabel rtCapacidadeGeladeira;
    private javax.swing.JLabel rtEspelhoGuardaRoupa;
    private javax.swing.JLabel rtFormatoMesa;
    private javax.swing.JLabel rtFreezerGeladeira;
    private javax.swing.JLabel rtId;
    private javax.swing.JLabel rtLucro;
    private javax.swing.JLabel rtNome;
    private javax.swing.JLabel rtQtdd;
    private javax.swing.JLabel rtQtddLugaresMesa;
    private javax.swing.JLabel rtQtddPortasGuardaRoupa;
    private javax.swing.JLabel rtTitulo;
    private javax.swing.JLabel rtValorCusto;
    private javax.swing.JLabel rtValorVenda;
    // End of variables declaration//GEN-END:variables
}
