//Victor Hugo Concolato Neves - 2576139

import java.sql.Date;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author conco
 */
public class FormRelVenda extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormRelVenda.class.getName());
    private DefaultTableModel modTab;
    private TableRowSorter<DefaultTableModel> sorter;
    private BdMovel bdMovel = BdMovel.getInstance();
    private BdPessoa bdPessoa = BdPessoa.getInstance();
    private BdVenda bdVenda = BdVenda.getInstance();
    
    //Inicio MÉTODO SINGLETON
    private static FormRelVenda relVendaInstance;

    private FormRelVenda() {
        initComponents();
    }
    
    public static FormRelVenda getInstance(){
        if(relVendaInstance==null){
            relVendaInstance = new FormRelVenda();
        }
        return relVendaInstance;
    }
    //Fim MÉTODO SINGLETON

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtTitulo = new javax.swing.JLabel();
        rtId = new javax.swing.JLabel();
        cxId = new javax.swing.JFormattedTextField();
        rtVendedor = new javax.swing.JLabel();
        cxVendedor = new javax.swing.JTextField();
        rtCliente = new javax.swing.JLabel();
        cxCliente = new javax.swing.JTextField();
        rtConsultaData = new javax.swing.JLabel();
        rtDataInicio = new javax.swing.JLabel();
        cxDataInicio = new javax.swing.JFormattedTextField();
        rtDataFim = new javax.swing.JLabel();
        cxDataFim = new javax.swing.JFormattedTextField();
        rtConsultaTipo = new javax.swing.JLabel();
        cbTipoMovel = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVenda = new javax.swing.JTable();
        btConsultar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        rtTotal = new javax.swing.JLabel();
        rtLucroTotal = new javax.swing.JLabel();
        rtValorTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        rtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rtTitulo.setText("Relatório de Vendas");

        rtId.setText("PROCURAR POR ID:");

        cxId.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        cxId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cxIdKeyReleased(evt);
            }
        });

        rtVendedor.setText("PROCURAR POR VENDEDOR:");

        cxVendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cxVendedorKeyReleased(evt);
            }
        });

        rtCliente.setText("PROCURAR POR CLIENTE:");

        cxCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cxClienteKeyReleased(evt);
            }
        });

        rtConsultaData.setText("CONSULTA ENTRE DATAS");

        rtDataInicio.setText("DE:");

        try {
            cxDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cxDataInicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cxDataInicioKeyReleased(evt);
            }
        });

        rtDataFim.setText("ATÉ:");

        try {
            cxDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cxDataFim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cxDataFimKeyReleased(evt);
            }
        });

        rtConsultaTipo.setText("CONSULTAR POR TIPO DE MÓVEL:");

        cbTipoMovel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Geladeira", "Guarda Roupa", "Mesa" }));
        cbTipoMovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoMovelActionPerformed(evt);
            }
        });

        tbVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Data", "Cliente", "Vendedor", "Quantidade Móveis", "Valor Total", "Lucro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbVendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbVenda);
        if (tbVenda.getColumnModel().getColumnCount() > 0) {
            tbVenda.getColumnModel().getColumn(0).setPreferredWidth(25);
        }

        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        rtTotal.setText("Total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rtTitulo)
                .addGap(392, 392, 392))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(btSair))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rtLucroTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cxId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rtId, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rtCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cxVendedor)
                            .addComponent(rtVendedor))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cxDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rtDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cxDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(rtConsultaData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rtConsultaTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbTipoMovel, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(rtTitulo)
                .addGap(30, 30, 30)
                .addComponent(rtConsultaData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rtId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtDataInicio)
                            .addComponent(rtDataFim))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cxDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cxDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rtConsultaTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTipoMovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rtCliente)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(cxVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(rtVendedor)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtTotal)
                    .addComponent(rtLucroTotal)
                    .addComponent(rtValorTotal))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConsultar)
                    .addComponent(btSair)
                    .addComponent(btLimpar))
                .addGap(17, 17, 17))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        consultar();
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limparForm();
    }//GEN-LAST:event_btLimparActionPerformed

    private void tbVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbVendaMouseClicked
        if(evt.getClickCount()>1){
            consultar();
        }
    }//GEN-LAST:event_tbVendaMouseClicked

    private void cxIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxIdKeyReleased
        filtrar();
    }//GEN-LAST:event_cxIdKeyReleased

    private void cxVendedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxVendedorKeyReleased
        filtrar();
    }//GEN-LAST:event_cxVendedorKeyReleased

    private void cxDataFimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxDataFimKeyReleased
        filtrar();
    }//GEN-LAST:event_cxDataFimKeyReleased

    private void cbTipoMovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoMovelActionPerformed
        filtrar();
    }//GEN-LAST:event_cbTipoMovelActionPerformed

    private void cxDataInicioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxDataInicioKeyReleased
        filtrar();
    }//GEN-LAST:event_cxDataInicioKeyReleased

    private void cxClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxClienteKeyReleased
        filtrar();
    }//GEN-LAST:event_cxClienteKeyReleased
    
    private void filtrar(){
        List<RowFilter<Object,Object>> filtros = new ArrayList<>();
        List<RowFilter<Object,Object>> filtroMovel = new ArrayList<>();
        String id = cxId.getText();
        String vendedor = cxVendedor.getText();
        String cliente = cxCliente.getText();
        String dataInicio = cxDataInicio.getText();
        String dataFim = cxDataFim.getText();
        String opcao = cbTipoMovel.getSelectedItem().toString();
        
        if(!id.isBlank()){
            filtros.add(RowFilter.regexFilter("(?i)\\b"+id, 0));
        }
        if(!vendedor.isBlank()){
            filtros.add(RowFilter.regexFilter("(?i)\\b"+vendedor, 3));
        }
        if(!cliente.isBlank()){
            filtros.add(RowFilter.regexFilter("(?i)\\b"+cliente, 2));
        }
        if(!dataInicio.contains(" ")){
            filtros.add(RowFilter.dateFilter(RowFilter.ComparisonType.AFTER, Date.valueOf(LocalDate.parse(dataInicio, DateTimeFormatter.ofPattern("dd/MM/yyyy"))), 1));
        }
        if(!dataFim.contains(" ")){
            filtros.add(RowFilter.dateFilter(RowFilter.ComparisonType.BEFORE, Date.valueOf(LocalDate.parse(dataFim, DateTimeFormatter.ofPattern("dd/MM/yyyy"))), 1));
        }
        if(!opcao.equals("Todos")){
            String nomeClasse;
            if(cbTipoMovel.getSelectedItem()==cbTipoMovel.getItemAt(2)){
                nomeClasse="GuardaRoupa";
            }else{
                nomeClasse=opcao;
            }
            
            for (int i = 0; i < modTab.getRowCount(); i++) {
                //Reflexividade
                for(ItemVenda itemVenda : bdVenda.getVenda(((Number)modTab.getValueAt(i, 0)).intValue()).getItensVenda()){
                    if(itemVenda.getMovel().getClass().getName().equals(nomeClasse)){
                        filtroMovel.add(RowFilter.regexFilter("\\b"+modTab.getValueAt(i, 0), 0));
                    }
                }                
            }
            filtros.add(RowFilter.orFilter(filtroMovel));
        }
        
        sorter.setRowFilter(RowFilter.andFilter(filtros));
        calcularTotal();
    }
    
    private void sair(){
        int escolha = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair da tela de relatório de vendas?", "Confirmar Saída", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if(escolha==0){
            limparForm();
            this.dispose();            
        }
    }
    
    private void limparForm(){
        cxId.setValue(null);
        cxVendedor.setText("");
        cxCliente.setText("");
        cxDataFim.setValue(null);
        cxDataInicio.setValue(null);
        cbTipoMovel.setSelectedIndex(0);
        valoresTabela();
    }
    
    private void consultar(){
        if(tbVenda.getSelectedRow()!=-1){
            FormConVenda form = FormConVenda.getInstance();
            //Reflexividade
            form.getCxId().setValue(tbVenda.getValueAt(tbVenda.getSelectedRow(), 0));
            form.procurar();
            form.setVisible(true); 
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, selecione uma linha na tabela para consultar os detalhes da venda.", "Nenhuma Linha Selecionada", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    private void calcularTotal(){
        double valor=0;
        double lucro=0;
        
        for(int i=0; i<sorter.getViewRowCount();i++){
            valor+=dinherioToNumber(String.valueOf(tbVenda.getValueAt(i, 5)));
            lucro+=dinherioToNumber(String.valueOf(tbVenda.getValueAt(i, 6)));
        }
        
        rtValorTotal.setText(formatarDinheiro(valor));
        rtLucroTotal.setText(formatarDinheiro(lucro));
    }
    
    private double dinherioToNumber(String valor){
        return Double.parseDouble(valor.replace("R$", "").replace(".", "").replace(",", ".").trim());
    }
    
    private String formatarDinheiro(double valor){
        String[] chars = String.valueOf(valor).replace(".", ",").split("");
        List<String> valorList = new ArrayList<>();
        int cont = 0;

        for (int i = chars.length - 1; i >= 0; i--) {
            String c = chars[i];
            valorList.add(0, c);
            if (c.equals(",")) {
                cont = 0;
                if(chars.length-i>1){
                    valorList.add("0");
                }
            }else if (++cont == 3 && i > 0) {
                valorList.add(0, ".");
                cont = 0;
            }
        }
        return "R$ " + String.join("", valorList) ;
    }
    
    public void valoresTabela(){        
        modTab = (DefaultTableModel) tbVenda.getModel();
        modTab.setRowCount(0);
        for (Venda venda : bdVenda.getBdVenda()) {
            //Reflexividade
            modTab.addRow(new Object[]{venda.getId(),venda.getData().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")),venda.getCliente().getNome(),venda.getVendedor().getNome(),venda.getItensVenda().size(), formatarDinheiro(venda.calcularValorTotal()), formatarDinheiro(venda.calcularLucroTotal())});
        }
        sorter = new TableRowSorter<>(modTab);
        tbVenda.setRowSorter(sorter);
        calcularTotal();
    }
    
    public void init(){
        this.setVisible(true);  
        valoresTabela();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormRelVenda().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JComboBox<String> cbTipoMovel;
    private javax.swing.JTextField cxCliente;
    private javax.swing.JFormattedTextField cxDataFim;
    private javax.swing.JFormattedTextField cxDataInicio;
    private javax.swing.JFormattedTextField cxId;
    private javax.swing.JTextField cxVendedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rtCliente;
    private javax.swing.JLabel rtConsultaData;
    private javax.swing.JLabel rtConsultaTipo;
    private javax.swing.JLabel rtDataFim;
    private javax.swing.JLabel rtDataInicio;
    private javax.swing.JLabel rtId;
    private javax.swing.JLabel rtLucroTotal;
    private javax.swing.JLabel rtTitulo;
    private javax.swing.JLabel rtTotal;
    private javax.swing.JLabel rtValorTotal;
    private javax.swing.JLabel rtVendedor;
    private javax.swing.JTable tbVenda;
    // End of variables declaration//GEN-END:variables
}
