//Victor Hugo Concolato Neves - 2576139

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author conco
 */
public class FormRelMovel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormRelMovel.class.getName());
    private DefaultTableModel modTab;
    private BdMovel bd = BdMovel.getInstance();
    private TableRowSorter<DefaultTableModel> sorter;
    
    //Inicio MÉTODO SINGLETON
    private static FormRelMovel relMovelInstance;
    
    private FormRelMovel() {
        initComponents();
    }
    
    public static FormRelMovel getInstance(){
        if(relMovelInstance==null){
            relMovelInstance = new FormRelMovel();
        }
        return relMovelInstance;
    }
    //Fim MÉTODO SINGLETON

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtTitulo = new javax.swing.JLabel();
        btGeladeira = new javax.swing.JCheckBox();
        btGuardaRoupa = new javax.swing.JCheckBox();
        btMesa = new javax.swing.JCheckBox();
        rtId = new javax.swing.JLabel();
        cxId = new javax.swing.JFormattedTextField();
        rtNome = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMovel = new javax.swing.JTable();
        btConsultar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        rtTotal = new javax.swing.JLabel();
        rtValorTotal = new javax.swing.JLabel();
        rtCustoTotal = new javax.swing.JLabel();
        rtQuantidadeTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        rtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rtTitulo.setText("Relatório de Móveis");

        btGeladeira.setText("Geladeira");
        btGeladeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGeladeiraActionPerformed(evt);
            }
        });

        btGuardaRoupa.setText("Guarda Roupa");
        btGuardaRoupa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardaRoupaActionPerformed(evt);
            }
        });

        btMesa.setText("Mesa");
        btMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMesaActionPerformed(evt);
            }
        });

        rtId.setText("PROCURAR POR ID:");

        cxId.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        cxId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cxIdKeyReleased(evt);
            }
        });

        rtNome.setText("PROCURAR POR NOME:");

        cxNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cxNomeKeyReleased(evt);
            }
        });

        tbMovel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Quantidade Estoque", "Custo", "Valor Unitário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbMovel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMovelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMovel);
        if (tbMovel.getColumnModel().getColumnCount() > 0) {
            tbMovel.getColumnModel().getColumn(0).setPreferredWidth(25);
        }

        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        rtTotal.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cxId, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rtId, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rtNome)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btConsultar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btLimpar)
                                .addGap(18, 18, 18)
                                .addComponent(btSair))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rtQuantidadeTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rtCustoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rtTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btGeladeira)
                                .addGap(18, 18, 18)
                                .addComponent(btGuardaRoupa)))
                        .addGap(18, 18, 18)
                        .addComponent(btMesa)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(rtTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGeladeira)
                    .addComponent(btGuardaRoupa)
                    .addComponent(btMesa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rtNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rtId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtTotal)
                    .addComponent(rtValorTotal)
                    .addComponent(rtCustoTotal)
                    .addComponent(rtQuantidadeTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConsultar)
                    .addComponent(btSair)
                    .addComponent(btLimpar))
                .addGap(17, 17, 17))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        try {
            consultar();
        } catch (ValorNumericoInvalidoException ex) {
            System.getLogger(FormRelMovel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limparForm();
    }//GEN-LAST:event_btLimparActionPerformed

    private void tbMovelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMovelMouseClicked
        if(evt.getClickCount()>1){
            try {
                consultar();
            } catch (ValorNumericoInvalidoException ex) {
                System.getLogger(FormRelMovel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
    }//GEN-LAST:event_tbMovelMouseClicked

    private void cxIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxIdKeyReleased
        filtrar();
    }//GEN-LAST:event_cxIdKeyReleased

    private void cxNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxNomeKeyReleased
        filtrar();
    }//GEN-LAST:event_cxNomeKeyReleased

    private void btGeladeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGeladeiraActionPerformed
        valoresTabela();
    }//GEN-LAST:event_btGeladeiraActionPerformed

    private void btGuardaRoupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardaRoupaActionPerformed
        valoresTabela();
    }//GEN-LAST:event_btGuardaRoupaActionPerformed

    private void btMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMesaActionPerformed
        valoresTabela();
    }//GEN-LAST:event_btMesaActionPerformed
    
    private void filtrar(){        
        sorter.setRowFilter(RowFilter.andFilter(Arrays.asList(RowFilter.regexFilter("(?i)\\b"+cxId.getText(), 0),RowFilter.regexFilter("(?i)\\b" + cxNome.getText(), 1))));
        calcularTotal();
    }
    
    private void sair(){
        int escolha = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair da tela de relatório de móveis?", "Confirmar Saída", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if(escolha==0){
            limparForm();
            this.dispose();            
        }
    }
    
    private void limparForm(){
        cxId.setValue(null);
        cxNome.setText("");
        btGeladeira.setSelected(false);
        btGuardaRoupa.setSelected(false);
        btMesa.setSelected(false);
        valoresTabela();
    }
    
    private void consultar() throws ValorNumericoInvalidoException{
        if(tbMovel.getSelectedRow()!=-1){
            FormConMovel form = FormConMovel.getInstance();
            form.init();
            //Reflexividade
            form.getCxId().setValue(tbMovel.getValueAt(tbMovel.getSelectedRow(), 0));
            form.procurar();
        }else{
           JOptionPane.showMessageDialog(null, "Por favor, selecione uma linha na tabela para consultar os detalhes da venda.", "Nenhuma Linha Selecionada", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    private double dinherioToNumber(String valor){
        return Double.parseDouble(valor.replace("R$", "").replace(".", "").replace(",", ".").trim());
    }
    
    private String formatarDinheiro(double valor){
        String[] chars = String.valueOf(valor).replace(".", ",").split("");
        List<String> valorList = new ArrayList<>();
        int cont = 0;

        for (int i = chars.length - 1; i >= 0; i--) {
            String c = chars[i];
            valorList.add(0, c);
            if (c.equals(",")) {
                cont = 0;
                if(chars.length-i>1){
                    valorList.add("0");
                }
            }else if (++cont == 3 && i > 0) {
                valorList.add(0, ".");
                cont = 0;
            }
        }
        return "R$ " + String.join("", valorList) ;
    }
    
    private void calcularTotal(){        
        int quantidade;
        int quantidadeTotal=0;
        double custoTotal=0;
        double valorTotal=0;
        
        
        for(int i=0; i<sorter.getViewRowCount();i++){
            quantidade = ((Number)tbMovel.getValueAt(i, 2)).intValue();
            quantidadeTotal+=quantidade;
            custoTotal+=dinherioToNumber((String) tbMovel.getValueAt(i, 3))*quantidade;
            valorTotal+=dinherioToNumber((String) tbMovel.getValueAt(i, 4))*quantidade;
        }
        
        rtQuantidadeTotal.setText(String.format("%d", quantidadeTotal));
        rtCustoTotal.setText(formatarDinheiro(custoTotal));
        rtValorTotal.setText(formatarDinheiro(valorTotal));
    }
    
    public void valoresTabela(){
        modTab = (DefaultTableModel) tbMovel.getModel();
        modTab.setRowCount(0);
        if(btGeladeira.isSelected()){
            for (Movel movel : bd.getBdMovel()) {
                if(movel.getClass().getName().equals("Geladeira")){
                    //Reflexividade
                    modTab.addRow(new Object[]{movel.getId(),movel.getNome(),movel.getQuantidadeEstoque(),formatarDinheiro(movel.getValor().getValorCusto()),formatarDinheiro(movel.getValor().getValorVenda())});
                }
            }
        }
        if(btGuardaRoupa.isSelected()){
            for (Movel movel : bd.getBdMovel()) {
                if(movel.getClass().getName().equals("GuardaRoupa")){
                    //Reflexividade
                    modTab.addRow(new Object[]{movel.getId(),movel.getNome(),movel.getQuantidadeEstoque(),formatarDinheiro(movel.getValor().getValorCusto()),formatarDinheiro(movel.getValor().getValorVenda())});
                }
            }
        }
        if(btMesa.isSelected()){
            for (Movel movel : bd.getBdMovel()) {
                if(movel.getClass().getName().equals("Mesa")){
                    //Reflexividade
                    modTab.addRow(new Object[]{movel.getId(),movel.getNome(),movel.getQuantidadeEstoque(),formatarDinheiro(movel.getValor().getValorCusto()),formatarDinheiro(movel.getValor().getValorVenda())});
                }
            }
        }        
        sorter = new TableRowSorter<>(modTab);
        tbMovel.setRowSorter(sorter);
        filtrar();
    }
    
    public void init(){
        this.setVisible(true);  
        btGeladeira.setSelected(true);
        btGuardaRoupa.setSelected(true);
        btMesa.setSelected(true);        
        valoresTabela();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormRelMovel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultar;
    private javax.swing.JCheckBox btGeladeira;
    private javax.swing.JCheckBox btGuardaRoupa;
    private javax.swing.JButton btLimpar;
    private javax.swing.JCheckBox btMesa;
    private javax.swing.JButton btSair;
    private javax.swing.JFormattedTextField cxId;
    private javax.swing.JTextField cxNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rtCustoTotal;
    private javax.swing.JLabel rtId;
    private javax.swing.JLabel rtNome;
    private javax.swing.JLabel rtQuantidadeTotal;
    private javax.swing.JLabel rtTitulo;
    private javax.swing.JLabel rtTotal;
    private javax.swing.JLabel rtValorTotal;
    private javax.swing.JTable tbMovel;
    // End of variables declaration//GEN-END:variables
}
