//Victor Hugo Concolato Neves - 2576139

import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author conco
 */
public class FormRelPessoa extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormRelPessoa.class.getName());
    private DefaultTableModel modTab;
    private TableRowSorter<DefaultTableModel> sorter;
    private BdPessoa bd = BdPessoa.getInstance();

    //Inicio MÉTODO SINGLETON
    private static FormRelPessoa relPessoaInstance;

    private FormRelPessoa() {
        initComponents();
    }
    
    public static FormRelPessoa getInstance(){
        if(relPessoaInstance==null){
            relPessoaInstance = new FormRelPessoa();
        }
        return relPessoaInstance;
    }
    //Fim MÉTODO SINGLETON

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtTitulo = new javax.swing.JLabel();
        btCliente = new javax.swing.JCheckBox();
        btVendedor = new javax.swing.JCheckBox();
        rtId = new javax.swing.JLabel();
        cxId = new javax.swing.JFormattedTextField();
        rtNome = new javax.swing.JLabel();
        cxNome = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPessoa = new javax.swing.JTable();
        btConsultar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        rtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rtTitulo.setText("Relatório de Pessoas");

        btCliente.setText("Cliente");
        btCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClienteActionPerformed(evt);
            }
        });

        btVendedor.setText("Vendedor");
        btVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVendedorActionPerformed(evt);
            }
        });

        rtId.setText("PROCURAR POR ID:");

        cxId.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        cxId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cxIdKeyReleased(evt);
            }
        });

        rtNome.setText("PROCURAR POR NOME:");

        cxNome.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        cxNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cxNomeKeyReleased(evt);
            }
        });

        tbPessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPessoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPessoaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPessoa);
        if (tbPessoa.getColumnModel().getColumnCount() > 0) {
            tbPessoa.getColumnModel().getColumn(0).setPreferredWidth(25);
        }

        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cxId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rtId, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rtNome)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(btSair)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btCliente)
                        .addGap(18, 18, 18)
                        .addComponent(btVendedor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(rtTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCliente)
                    .addComponent(btVendedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rtNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rtId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConsultar)
                    .addComponent(btSair)
                    .addComponent(btLimpar))
                .addGap(17, 17, 17))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        consultar();
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limparForm();
    }//GEN-LAST:event_btLimparActionPerformed

    private void tbPessoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPessoaMouseClicked
        if(evt.getClickCount()>1){
            consultar();
        }
    }//GEN-LAST:event_tbPessoaMouseClicked

    private void cxIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxIdKeyReleased
        filtrar();
    }//GEN-LAST:event_cxIdKeyReleased

    private void cxNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxNomeKeyReleased
        filtrar();
    }//GEN-LAST:event_cxNomeKeyReleased

    private void btClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClienteActionPerformed
        valoresTabela();
    }//GEN-LAST:event_btClienteActionPerformed

    private void btVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVendedorActionPerformed
        valoresTabela();
    }//GEN-LAST:event_btVendedorActionPerformed
    
    private void filtrar(){        
        sorter.setRowFilter(RowFilter.andFilter(Arrays.asList(RowFilter.regexFilter("(?i)\\b"+cxId.getText(), 0),RowFilter.regexFilter("(?i)\\b"+ cxNome.getText(), 1))));
    }
    
    private void sair(){
        int escolha = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair da tela de relatório de pessoas?", "Confirmar Saída", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if(escolha==0){
            limparForm();
            this.dispose();            
        }
    }
    
    private void limparForm(){
        cxId.setValue(null);
        cxNome.setText("");
        btCliente.setSelected(false);
        btVendedor.setSelected(false);
        valoresTabela();
    }
    
    private void consultar(){
        if(tbPessoa.getSelectedRow()!=-1){
           FormConPessoa form = FormConPessoa.getInstance();
           //Reflexividade
            form.getCxId().setValue(tbPessoa.getValueAt(tbPessoa.getSelectedRow(), 0));
            form.procurar();
            form.setVisible(true); 
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, selecione uma linha na tabela para consultar os detalhes da pessoa.", "Nenhuma Linha Selecionada", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    public void valoresTabela(){        
        modTab = (DefaultTableModel) tbPessoa.getModel();
        modTab.setRowCount(0);
        modTab.setColumnCount(2);
        if(btCliente.isSelected() && btVendedor.isSelected()){            
            for (Pessoa pessoa : bd.getBdPessoa()) {
                modTab.addRow(new Object[]{pessoa.getId(),pessoa.getNome()});
            }
        }else{
            double valor;
            if(btCliente.isSelected()){
                modTab.addColumn("Telefone");
                modTab.addColumn("Email");
                modTab.addColumn("Quantidade compras");
                modTab.addColumn("Valor Gasto Total");
                for (Pessoa pessoa : bd.getBdPessoa()) {
                    if(pessoa.getClass().getName().equals("Cliente")){
                        Cliente c = (Cliente) pessoa;
                        int quantidade=0;
                        valor=0;
                        for (Venda venda : BdVenda.getInstance().getBdVenda()) {
                            if(venda.getCliente()==c){
                                quantidade++;
                                valor+=venda.calcularValorTotal();
                            }
                        }
                        modTab.addRow(new Object[]{c.getId(),c.getNome(),c.getTelefone(),c.getEmail(),quantidade,valor});
                    }
                }
            }
            if(btVendedor.isSelected()){                
                modTab.addColumn("Salário");
                modTab.addColumn("Quantidade de vendas");
                modTab.addColumn("Valor Total Vendido");
                for (Pessoa pessoa : bd.getBdPessoa()) {
                    if(pessoa.getClass().getName().equals("Vendedor")){
                        Vendedor v = (Vendedor) pessoa;
                        valor=0;
                        for (Venda venda : BdVenda.getInstance().getBdVenda()) {
                            if(venda.getVendedor()==v){
                                valor+=venda.calcularValorTotal();
                            }
                        }
                        modTab.addRow(new Object[]{v.getId(),v.getNome(),v.getSalario(),v.getQuantidadeVendas(),valor});
                    
                    }
                }
            }   
        }        
        sorter = new TableRowSorter<>(modTab);
        tbPessoa.setRowSorter(sorter);
        
    }
    
    public void init(){
        this.setVisible(true);  
        btCliente.setSelected(true);
        btVendedor.setSelected(true);
        valoresTabela();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormRelPessoa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox btCliente;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JCheckBox btVendedor;
    private javax.swing.JFormattedTextField cxId;
    private javax.swing.JFormattedTextField cxNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rtId;
    private javax.swing.JLabel rtNome;
    private javax.swing.JLabel rtTitulo;
    private javax.swing.JTable tbPessoa;
    // End of variables declaration//GEN-END:variables
}
