//Victor Hugo Concolato Neves - 2576139

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author conco
 */
public class FormCadMovel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCadMovel.class.getName());
    private BdMovel bd = BdMovel.getInstance();
    private Valor valor;
    
    //Inicio MÉTODO SINGLETON
    private static FormCadMovel cadMovelInstance;
    
    private FormCadMovel() {
        initComponents();
    }
    
    public static FormCadMovel getInstance(){
        if(cadMovelInstance==null){
            cadMovelInstance = new FormCadMovel();
        }
        return cadMovelInstance;
    }
    //Fim MÉTODO SINGLETON

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGrupoEspelho = new javax.swing.ButtonGroup();
        btGrupoFreezer = new javax.swing.ButtonGroup();
        rtTitulo = new javax.swing.JLabel();
        rtEscolha = new javax.swing.JLabel();
        cbEscolha = new javax.swing.JComboBox<>();
        panCadMovel = new javax.swing.JPanel();
        rtId = new javax.swing.JLabel();
        cxId = new javax.swing.JFormattedTextField();
        rtNome = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        rtQtdd = new javax.swing.JLabel();
        cxQtdd = new javax.swing.JFormattedTextField();
        rtValorCusto = new javax.swing.JLabel();
        cxValorCusto = new javax.swing.JFormattedTextField();
        rtValorVenda = new javax.swing.JLabel();
        cxValorVenda = new javax.swing.JFormattedTextField();
        rtLucro = new javax.swing.JLabel();
        cxLucro = new javax.swing.JFormattedTextField();
        panCadGuardaRoupa = new javax.swing.JPanel();
        rtQtddPortasGuardaRoupa = new javax.swing.JLabel();
        cxQtddPortasGuardaRoupa = new javax.swing.JFormattedTextField();
        rtEspelhoGuardaRoupa = new javax.swing.JLabel();
        btEspelhoSim = new javax.swing.JRadioButton();
        btEspelhoNao = new javax.swing.JRadioButton();
        panCadGeladeira = new javax.swing.JPanel();
        rtCapacidadeGeladeira = new javax.swing.JLabel();
        cxCapacidadeGeladeira = new javax.swing.JFormattedTextField();
        rtFreezerGeladeira = new javax.swing.JLabel();
        btFreezerSim = new javax.swing.JRadioButton();
        btFreezerNao = new javax.swing.JRadioButton();
        panCadMesa = new javax.swing.JPanel();
        rtQtddLugaresMesa = new javax.swing.JLabel();
        cxQtddLugaresMesa = new javax.swing.JFormattedTextField();
        rtFormatoMesa = new javax.swing.JLabel();
        cxFormatoMesa = new javax.swing.JTextField();
        btCadastrar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        rtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rtTitulo.setText("Cadastro de Móveis");

        rtEscolha.setText("Selecione o que quer cadastrar");

        cbEscolha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Geladeira", "Guarda Roupa", "Mesa" }));
        cbEscolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEscolhaActionPerformed(evt);
            }
        });

        rtId.setText("ID:");

        cxId.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        rtNome.setText("Nome:");

        rtQtdd.setText("Quantidade em estoque:");

        cxQtdd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        rtValorCusto.setText("Valor de custo:");

        cxValorCusto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        cxValorCusto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cxValorCustoFocusLost(evt);
            }
        });
        cxValorCusto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cxValorCustoKeyReleased(evt);
            }
        });

        rtValorVenda.setText("Valor de venda:");

        cxValorVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        cxValorVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cxValorVendaFocusLost(evt);
            }
        });
        cxValorVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cxValorVendaKeyReleased(evt);
            }
        });

        rtLucro.setText("Lucro:");

        cxLucro.setEditable(false);
        cxLucro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        cxLucro.setEnabled(false);

        javax.swing.GroupLayout panCadMovelLayout = new javax.swing.GroupLayout(panCadMovel);
        panCadMovel.setLayout(panCadMovelLayout);
        panCadMovelLayout.setHorizontalGroup(
            panCadMovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCadMovelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCadMovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtQtdd)
                    .addComponent(rtValorCusto)
                    .addComponent(rtValorVenda)
                    .addComponent(rtLucro))
                .addGap(47, 47, 47)
                .addGroup(panCadMovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxNome, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addGroup(panCadMovelLayout.createSequentialGroup()
                        .addGroup(panCadMovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cxValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cxValorCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cxQtdd, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cxId, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panCadMovelLayout.setVerticalGroup(
            panCadMovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCadMovelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(panCadMovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtId)
                    .addComponent(cxId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panCadMovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panCadMovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtQtdd)
                    .addComponent(cxQtdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panCadMovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtValorCusto)
                    .addComponent(cxValorCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panCadMovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtValorVenda)
                    .addComponent(cxValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panCadMovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtLucro)
                    .addComponent(cxLucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        rtQtddPortasGuardaRoupa.setText("Quantidade de portas:");

        cxQtddPortasGuardaRoupa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        rtEspelhoGuardaRoupa.setText("Possui espelho?");

        btGrupoEspelho.add(btEspelhoSim);
        btEspelhoSim.setText("Sim");

        btGrupoEspelho.add(btEspelhoNao);
        btEspelhoNao.setText("Não");

        javax.swing.GroupLayout panCadGuardaRoupaLayout = new javax.swing.GroupLayout(panCadGuardaRoupa);
        panCadGuardaRoupa.setLayout(panCadGuardaRoupaLayout);
        panCadGuardaRoupaLayout.setHorizontalGroup(
            panCadGuardaRoupaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCadGuardaRoupaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCadGuardaRoupaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtEspelhoGuardaRoupa)
                    .addComponent(rtQtddPortasGuardaRoupa))
                .addGap(59, 59, 59)
                .addGroup(panCadGuardaRoupaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCadGuardaRoupaLayout.createSequentialGroup()
                        .addComponent(btEspelhoSim)
                        .addGap(36, 36, 36)
                        .addComponent(btEspelhoNao))
                    .addComponent(cxQtddPortasGuardaRoupa, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );
        panCadGuardaRoupaLayout.setVerticalGroup(
            panCadGuardaRoupaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCadGuardaRoupaLayout.createSequentialGroup()
                .addGroup(panCadGuardaRoupaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtQtddPortasGuardaRoupa)
                    .addComponent(cxQtddPortasGuardaRoupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panCadGuardaRoupaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtEspelhoGuardaRoupa)
                    .addComponent(btEspelhoSim)
                    .addComponent(btEspelhoNao)))
        );

        rtCapacidadeGeladeira.setText("Capacidade (Litros):");

        cxCapacidadeGeladeira.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        rtFreezerGeladeira.setText("Possui Freezer?");

        btGrupoFreezer.add(btFreezerSim);
        btFreezerSim.setText("Sim");

        btGrupoFreezer.add(btFreezerNao);
        btFreezerNao.setText("Não");

        javax.swing.GroupLayout panCadGeladeiraLayout = new javax.swing.GroupLayout(panCadGeladeira);
        panCadGeladeira.setLayout(panCadGeladeiraLayout);
        panCadGeladeiraLayout.setHorizontalGroup(
            panCadGeladeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCadGeladeiraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCadGeladeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtCapacidadeGeladeira)
                    .addComponent(rtFreezerGeladeira))
                .addGap(71, 71, 71)
                .addGroup(panCadGeladeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxCapacidadeGeladeira, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panCadGeladeiraLayout.createSequentialGroup()
                        .addComponent(btFreezerSim)
                        .addGap(36, 36, 36)
                        .addComponent(btFreezerNao)))
                .addGap(43, 43, 43))
        );
        panCadGeladeiraLayout.setVerticalGroup(
            panCadGeladeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCadGeladeiraLayout.createSequentialGroup()
                .addGroup(panCadGeladeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtCapacidadeGeladeira)
                    .addComponent(cxCapacidadeGeladeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panCadGeladeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtFreezerGeladeira)
                    .addComponent(btFreezerSim)
                    .addComponent(btFreezerNao)))
        );

        rtQtddLugaresMesa.setText("Quantidade de lugares:");

        cxQtddLugaresMesa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        rtFormatoMesa.setText("Formato:");

        javax.swing.GroupLayout panCadMesaLayout = new javax.swing.GroupLayout(panCadMesa);
        panCadMesa.setLayout(panCadMesaLayout);
        panCadMesaLayout.setHorizontalGroup(
            panCadMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCadMesaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCadMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtQtddLugaresMesa)
                    .addComponent(rtFormatoMesa))
                .addGroup(panCadMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCadMesaLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(cxQtddLugaresMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCadMesaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxFormatoMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panCadMesaLayout.setVerticalGroup(
            panCadMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCadMesaLayout.createSequentialGroup()
                .addGroup(panCadMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtQtddLugaresMesa)
                    .addComponent(cxQtddLugaresMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panCadMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtFormatoMesa)
                    .addComponent(cxFormatoMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btCadastrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btLimpar)
                                .addGap(18, 18, 18)
                                .addComponent(btSair))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(panCadMovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rtEscolha)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(panCadMesa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(panCadGuardaRoupa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(panCadGeladeira, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(rtTitulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(rtTitulo)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtEscolha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panCadMovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panCadGuardaRoupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panCadGeladeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panCadMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar)
                    .addComponent(btSair)
                    .addComponent(btLimpar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbEscolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEscolhaActionPerformed
        verificaEscolha();
    }//GEN-LAST:event_cbEscolhaActionPerformed

    private void cxValorVendaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxValorVendaKeyReleased
        try {
            calculaLucro();
        } catch (ValorNumericoInvalidoException ex) {
            JOptionPane.showMessageDialog(null, ex.impErro(), "Erro", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_cxValorVendaKeyReleased

    private void cxValorCustoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxValorCustoKeyReleased
        try {
            calculaLucro();
        } catch (ValorNumericoInvalidoException ex) {
            JOptionPane.showMessageDialog(null, ex.impErro(), "Erro", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_cxValorCustoKeyReleased

    private void cxValorCustoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cxValorCustoFocusLost
        try {
            calculaLucro();
        } catch (ValorNumericoInvalidoException ex) {
            JOptionPane.showMessageDialog(null, ex.impErro(), "Erro", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_cxValorCustoFocusLost

    private void cxValorVendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cxValorVendaFocusLost
        try {
            calculaLucro();
        } catch (ValorNumericoInvalidoException ex) {
            JOptionPane.showMessageDialog(null, ex.impErro(), "Erro", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_cxValorVendaFocusLost

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        try {
            cadastrar();
        } catch (ValorNumericoInvalidoException ex) {
            JOptionPane.showMessageDialog(null, ex.impErro(), "Erro", JOptionPane.OK_OPTION);
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limparForm();
    }//GEN-LAST:event_btLimparActionPerformed
    
    private void cadastrar() throws ValorNumericoInvalidoException{
        if(verificaPreenchimento()){
            Movel movel = null;
            if(cbEscolha.getSelectedItem()==cbEscolha.getItemAt(1)){
                movel = new Geladeira();
                Geladeira geladeira = (Geladeira) movel;                
                geladeira.setCapacidadeLitros(((Number) cxCapacidadeGeladeira.getValue()).intValue());
                geladeira.setFreezer(btFreezerSim.isSelected());
            }else if(cbEscolha.getSelectedItem()==cbEscolha.getItemAt(2)){
                movel = new GuardaRoupa();
                GuardaRoupa guardaRoupa = (GuardaRoupa) movel;
                guardaRoupa.setQuantidadePortas(((Number)cxQtddPortasGuardaRoupa.getValue()).intValue());
                guardaRoupa.setEspelho(btEspelhoSim.isSelected());
            }else if(cbEscolha.getSelectedItem()==cbEscolha.getItemAt(3)){
                movel = new Mesa();
                Mesa mesa = (Mesa) movel;
                mesa.setFormato(cxFormatoMesa.getText());
                mesa.setQuantidadeLugares(((Number) cxQtddLugaresMesa.getValue()).intValue());
            }
            movel.setId(((Number)cxId.getValue()).intValue());
            movel.setNome(cxNome.getText());
            movel.setQuantidadeEstoque(((Number)cxQtdd.getValue()).intValue());
            movel.setValor(valor);
            bd.cadMovel(movel);
            valor = new Valor();
            
            JOptionPane.showMessageDialog(
                    null,
                    "O móvel foi cadastrado com sucesso!\n"
                    +movel.exibirInformacoes(),
                    "Cadastro Concluído",
                    JOptionPane.INFORMATION_MESSAGE);
            limparForm();
            hideForm();
        }else{
            JOptionPane.showMessageDialog(null, "Todos os campos do formulário são obrigatórios. Por favor, preencha-os para continuar.", "Campos Obrigatórios", JOptionPane.OK_OPTION);
        }
    }
    
    private boolean verificaPreenchimento(){
        if(cbEscolha.getSelectedItem()!=cbEscolha.getItemAt(0)){
            if(cxId.getText().isBlank() || cxNome.getText().isBlank() || cxQtdd.getText().isBlank() || cxValorCusto.getText().isBlank() || cxValorVenda.getText().isBlank()){
                return false;
            }
            if(cbEscolha.getSelectedItem()==cbEscolha.getItemAt(1)){
                if(cxCapacidadeGeladeira.getText().isBlank() || btGrupoFreezer.getSelection()==null){
                    return false;
                }
            }else if(cbEscolha.getSelectedItem()==cbEscolha.getItemAt(2)){
                if(cxQtddPortasGuardaRoupa.getText().isBlank() || btGrupoEspelho.getSelection()==null){
                    return false;
                }
            }else if(cbEscolha.getSelectedItem()==cbEscolha.getItemAt(3)){
                if(cxQtddLugaresMesa.getText().isBlank() || cxFormatoMesa.getText().isBlank()){
                    return false;
                }
            }
        }else{
            return false;
        }    
        return true;
    }
    
    private void sair(){
        int escolha = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair da tela de cadastro de móveis?", "Confirmar Saída", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if(escolha==0){
            limparForm();
            this.dispose();            
        }
    }
    
    private void limparForm(){
        cxId.setValue(null);
        cxNome.setText("");
        cxQtdd.setValue(null);
        cxValorCusto.setValue(null);
        cxValorVenda.setValue(null);
        cxLucro.setValue(null);
        cxCapacidadeGeladeira.setValue(null);
        cxFormatoMesa.setText("");
        cxQtddLugaresMesa.setValue(null);
        cxQtddPortasGuardaRoupa.setValue(null);
        btGrupoEspelho.clearSelection();
        btGrupoFreezer.clearSelection();
        cbEscolha.setSelectedItem(cbEscolha.getItemAt(0));
    }
    
    private double replaceComma(String number){
        return Double.parseDouble(number.replace(".","").replace(',', '.'));
    }
    
    private void calculaLucro() throws ValorNumericoInvalidoException{
        if(!(cxValorVenda.getText().isBlank() || cxValorCusto.getText().isBlank())){
            valor.setValorCusto(replaceComma(cxValorCusto.getText()));
            valor.setValorVenda(replaceComma(cxValorVenda.getText()));            
            cxLucro.setValue(valor.getLucro());
        }else{
            cxLucro.setValue(null);
        }
    }
    
    private void verificaEscolha(){
        hideForm();
        Object itemSelecionado = cbEscolha.getSelectedItem();
        if(!(itemSelecionado.equals(cbEscolha.getItemAt(0)))){
            btCadastrar.setVisible(true);
            btLimpar.setVisible(true);
            panCadMovel.setVisible(true);
            if(itemSelecionado.equals(cbEscolha.getItemAt(1))){
                panCadGeladeira.setVisible(true);
            }else if(itemSelecionado.equals(cbEscolha.getItemAt(2))){
                panCadGuardaRoupa.setVisible(true);
            }else if(itemSelecionado.equals(cbEscolha.getItemAt(3))){
                panCadMesa.setVisible(true);
            }
        }
    }
    
    public void init(){
        this.setVisible(true);
        this.hideForm();            
        valor = new Valor();
    }
    
    private void hideForm(){
        panCadGeladeira.setVisible(false);
        panCadGuardaRoupa.setVisible(false);
        panCadMesa.setVisible(false);
        panCadMovel.setVisible(false);
        btCadastrar.setVisible(false);
        btLimpar.setVisible(false);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormCadMovel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JRadioButton btEspelhoNao;
    private javax.swing.JRadioButton btEspelhoSim;
    private javax.swing.JRadioButton btFreezerNao;
    private javax.swing.JRadioButton btFreezerSim;
    private javax.swing.ButtonGroup btGrupoEspelho;
    private javax.swing.ButtonGroup btGrupoFreezer;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JComboBox<String> cbEscolha;
    private javax.swing.JFormattedTextField cxCapacidadeGeladeira;
    private javax.swing.JTextField cxFormatoMesa;
    private javax.swing.JFormattedTextField cxId;
    private javax.swing.JFormattedTextField cxLucro;
    private javax.swing.JTextField cxNome;
    private javax.swing.JFormattedTextField cxQtdd;
    private javax.swing.JFormattedTextField cxQtddLugaresMesa;
    private javax.swing.JFormattedTextField cxQtddPortasGuardaRoupa;
    private javax.swing.JFormattedTextField cxValorCusto;
    private javax.swing.JFormattedTextField cxValorVenda;
    private javax.swing.JPanel panCadGeladeira;
    private javax.swing.JPanel panCadGuardaRoupa;
    private javax.swing.JPanel panCadMesa;
    private javax.swing.JPanel panCadMovel;
    private javax.swing.JLabel rtCapacidadeGeladeira;
    private javax.swing.JLabel rtEscolha;
    private javax.swing.JLabel rtEspelhoGuardaRoupa;
    private javax.swing.JLabel rtFormatoMesa;
    private javax.swing.JLabel rtFreezerGeladeira;
    private javax.swing.JLabel rtId;
    private javax.swing.JLabel rtLucro;
    private javax.swing.JLabel rtNome;
    private javax.swing.JLabel rtQtdd;
    private javax.swing.JLabel rtQtddLugaresMesa;
    private javax.swing.JLabel rtQtddPortasGuardaRoupa;
    private javax.swing.JLabel rtTitulo;
    private javax.swing.JLabel rtValorCusto;
    private javax.swing.JLabel rtValorVenda;
    // End of variables declaration//GEN-END:variables
}
