//Victor Hugo Concolato Neves - 2576139

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author conco
 */
public class FormCadPessoa extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCadPessoa.class.getName());
    private BdPessoa bd = BdPessoa.getInstance();

    //Inicio MÉTODO SINGLETON
    private static FormCadPessoa cadPessoaInstance;
    
    private FormCadPessoa() {
        initComponents();
    }
    
    public static FormCadPessoa getInstance(){
        if(cadPessoaInstance==null){
            cadPessoaInstance = new FormCadPessoa();
        }
        return cadPessoaInstance;
    }
    //Fim MÉTODO SINGLETON

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtTitulo = new javax.swing.JLabel();
        rtEscolha = new javax.swing.JLabel();
        cbEscolha = new javax.swing.JComboBox<>();
        panCadPessoa = new javax.swing.JPanel();
        rtId = new javax.swing.JLabel();
        cxId = new javax.swing.JFormattedTextField();
        rtNome = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        panCadCliente = new javax.swing.JPanel();
        rtEmailCliente = new javax.swing.JLabel();
        cxEmailCliente = new javax.swing.JTextField();
        rtTelefoneCliente = new javax.swing.JLabel();
        cxTelefoneCliente = new javax.swing.JTextField();
        panCadVendedor = new javax.swing.JPanel();
        rtSalarioVendedor = new javax.swing.JLabel();
        cxSalarioVendedor = new javax.swing.JFormattedTextField();
        rtQtddVendasVendedor = new javax.swing.JLabel();
        cxQtddVendasVendedor = new javax.swing.JFormattedTextField();
        btCadastrar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        rtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rtTitulo.setText("Cadastro de Pessoas");

        rtEscolha.setText("Selecione o que quer cadastrar");

        cbEscolha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Cliente", "Vendedor" }));
        cbEscolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEscolhaActionPerformed(evt);
            }
        });

        rtId.setText("ID:");

        cxId.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        rtNome.setText("Nome:");

        javax.swing.GroupLayout panCadPessoaLayout = new javax.swing.GroupLayout(panCadPessoa);
        panCadPessoa.setLayout(panCadPessoaLayout);
        panCadPessoaLayout.setHorizontalGroup(
            panCadPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCadPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCadPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140)
                .addGroup(panCadPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxNome, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addGroup(panCadPessoaLayout.createSequentialGroup()
                        .addComponent(cxId, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panCadPessoaLayout.setVerticalGroup(
            panCadPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCadPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCadPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtId)
                    .addComponent(cxId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panCadPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        rtEmailCliente.setText("Email:");

        rtTelefoneCliente.setText("Telefone:");

        javax.swing.GroupLayout panCadClienteLayout = new javax.swing.GroupLayout(panCadCliente);
        panCadCliente.setLayout(panCadClienteLayout);
        panCadClienteLayout.setHorizontalGroup(
            panCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCadClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtEmailCliente)
                    .addComponent(rtTelefoneCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxEmailCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxTelefoneCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        panCadClienteLayout.setVerticalGroup(
            panCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCadClienteLayout.createSequentialGroup()
                .addGroup(panCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtEmailCliente)
                    .addComponent(cxEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtTelefoneCliente)
                    .addComponent(cxTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        rtSalarioVendedor.setText("Salário:");

        cxSalarioVendedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        rtQtddVendasVendedor.setText("Quantidade de Vendas");

        cxQtddVendasVendedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        javax.swing.GroupLayout panCadVendedorLayout = new javax.swing.GroupLayout(panCadVendedor);
        panCadVendedor.setLayout(panCadVendedorLayout);
        panCadVendedorLayout.setHorizontalGroup(
            panCadVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCadVendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCadVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtSalarioVendedor)
                    .addComponent(rtQtddVendasVendedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panCadVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxSalarioVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxQtddVendasVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        panCadVendedorLayout.setVerticalGroup(
            panCadVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCadVendedorLayout.createSequentialGroup()
                .addGroup(panCadVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtSalarioVendedor)
                    .addComponent(cxSalarioVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panCadVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtQtddVendasVendedor)
                    .addComponent(cxQtddVendasVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panCadCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panCadVendedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panCadPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rtEscolha)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btCadastrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btLimpar)
                                .addGap(18, 18, 18)
                                .addComponent(btSair)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(rtTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(rtTitulo)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtEscolha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panCadPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panCadVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panCadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar)
                    .addComponent(btSair)
                    .addComponent(btLimpar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbEscolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEscolhaActionPerformed
        verificaEscolha();
    }//GEN-LAST:event_cbEscolhaActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        try {
            cadastrar();
        } catch (ValorNumericoInvalidoException ex) {
            JOptionPane.showMessageDialog(null, ex.impErro(), "Erro", JOptionPane.OK_OPTION);
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limparForm();
    }//GEN-LAST:event_btLimparActionPerformed
    
    private void cadastrar() throws ValorNumericoInvalidoException{
        if(verificaPreenchimento()){
            Pessoa pessoa = null;
            if(cbEscolha.getSelectedItem()==cbEscolha.getItemAt(1)){
                pessoa = new Cliente();
                Cliente cliente = (Cliente) pessoa;
                cliente.setEmail(cxEmailCliente.getText());
                cliente.setTelefone(cxTelefoneCliente.getText());
            }else if(cbEscolha.getSelectedItem()==cbEscolha.getItemAt(2)){
                pessoa = new Vendedor();
                Vendedor vendedor = (Vendedor) pessoa;
                vendedor.setQuantidadeVendas(((Number) cxQtddVendasVendedor.getValue()).intValue());
                vendedor.setSalario(((Number) cxSalarioVendedor.getValue()).doubleValue());
            }
            pessoa.setId(((Number)cxId.getValue()).intValue());
            pessoa.setNome(cxNome.getText());       
            bd.cadPessoa(pessoa);
            JOptionPane.showMessageDialog(null,
                    "A pessoa foi cadastrada com sucesso!\n"
                    +pessoa.exibirInformacoes(),
                    "Cadastro Concluído",
                    JOptionPane.INFORMATION_MESSAGE);
            limparForm();
            hideForm();
        }else{
            JOptionPane.showMessageDialog(null, "Todos os campos do formulário são obrigatórios. Por favor, preencha-os para continuar.", "Campos Obrigatórios", JOptionPane.OK_OPTION);
        }
    }
    
    private boolean verificaPreenchimento(){
        if(cbEscolha.getSelectedItem()!=cbEscolha.getItemAt(0)){
            if(cxId.getText().isBlank() || cxNome.getText().isBlank()){
                return false;
            }
            if(cbEscolha.getSelectedItem()==cbEscolha.getItemAt(1)){
                if(cxEmailCliente.getText().isBlank() || cxTelefoneCliente.getText().isBlank()){
                    return false;
                }
            }else if(cbEscolha.getSelectedItem()==cbEscolha.getItemAt(2)){
                if(cxQtddVendasVendedor.getText().isBlank() || cxSalarioVendedor.getText().isBlank()){
                    return false;
                }
            }
        }else{
            return false;
        }    
        return true;
    }
    
    private void sair(){
        int escolha = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair da tela de cadastro de pessoas?", "Confirmar Saída", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if(escolha==0){
            limparForm();
            this.dispose();            
        }
    }
    
    private void limparForm(){
        cxId.setValue(null);
        cxNome.setText("");
        cxQtddVendasVendedor.setValue(null);
        cxSalarioVendedor.setValue(null);
        cxEmailCliente.setText("");
        cxTelefoneCliente.setText(null);
        cbEscolha.setSelectedItem(cbEscolha.getItemAt(0));
    }
    
    private void verificaEscolha(){
        hideForm();
        Object itemSelecionado = cbEscolha.getSelectedItem();
        if(!(itemSelecionado.equals(cbEscolha.getItemAt(0)))){
            btCadastrar.setVisible(true);
            btLimpar.setVisible(true);
            panCadPessoa.setVisible(true);
            if(itemSelecionado.equals(cbEscolha.getItemAt(1))){
                panCadCliente.setVisible(true);
            }else if(itemSelecionado.equals(cbEscolha.getItemAt(2))){
                panCadVendedor.setVisible(true);
            }
        }
    }
    
    public void init(){
        this.setVisible(true);
        this.hideForm();
    }
    
    private void hideForm(){
        panCadVendedor.setVisible(false);
        panCadCliente.setVisible(false);
        panCadPessoa.setVisible(false);
        btCadastrar.setVisible(false);
        btLimpar.setVisible(false);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormCadPessoa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JComboBox<String> cbEscolha;
    private javax.swing.JTextField cxEmailCliente;
    private javax.swing.JFormattedTextField cxId;
    private javax.swing.JTextField cxNome;
    private javax.swing.JFormattedTextField cxQtddVendasVendedor;
    private javax.swing.JFormattedTextField cxSalarioVendedor;
    private javax.swing.JTextField cxTelefoneCliente;
    private javax.swing.JPanel panCadCliente;
    private javax.swing.JPanel panCadPessoa;
    private javax.swing.JPanel panCadVendedor;
    private javax.swing.JLabel rtEmailCliente;
    private javax.swing.JLabel rtEscolha;
    private javax.swing.JLabel rtId;
    private javax.swing.JLabel rtNome;
    private javax.swing.JLabel rtQtddVendasVendedor;
    private javax.swing.JLabel rtSalarioVendedor;
    private javax.swing.JLabel rtTelefoneCliente;
    private javax.swing.JLabel rtTitulo;
    // End of variables declaration//GEN-END:variables
}
