//Victor Hugo Concolato Neves - 2576139

import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author conco
 */
public class FormConPessoa extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormConPessoa.class.getName());
    private BdPessoa bd = BdPessoa.getInstance();
    private Pessoa p;

    //Inicio MÉTODO SINGLETON
    private static FormConPessoa conPessoaInstance;

    private FormConPessoa() {
        initComponents();
    }
    
    public static FormConPessoa getInstance(){
        if(conPessoaInstance==null){
            conPessoaInstance = new FormConPessoa();
        }
        return conPessoaInstance;
    }
    //Fim MÉTODO SINGLETON

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtTitulo = new javax.swing.JLabel();
        panConPessoa = new javax.swing.JPanel();
        rtNome = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        panConCliente = new javax.swing.JPanel();
        rtEmailCliente = new javax.swing.JLabel();
        cxEmailCliente = new javax.swing.JTextField();
        rtTelefoneCliente = new javax.swing.JLabel();
        cxTelefoneCliente = new javax.swing.JTextField();
        panConVendedor = new javax.swing.JPanel();
        rtSalarioVendedor = new javax.swing.JLabel();
        cxSalarioVendedor = new javax.swing.JFormattedTextField();
        rtQtddVendasVendedor = new javax.swing.JLabel();
        cxQtddVendasVendedor = new javax.swing.JFormattedTextField();
        btSair = new javax.swing.JButton();
        cxId = new javax.swing.JFormattedTextField();
        rtId = new javax.swing.JLabel();
        btProcurar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        rtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rtTitulo.setText("Consulta de Pessoas");

        rtNome.setText("Nome:");

        javax.swing.GroupLayout panConPessoaLayout = new javax.swing.GroupLayout(panConPessoa);
        panConPessoa.setLayout(panConPessoaLayout);
        panConPessoaLayout.setHorizontalGroup(
            panConPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(cxNome, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addContainerGap())
        );
        panConPessoaLayout.setVerticalGroup(
            panConPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConPessoaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panConPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        rtEmailCliente.setText("Email:");

        rtTelefoneCliente.setText("Telefone:");

        javax.swing.GroupLayout panConClienteLayout = new javax.swing.GroupLayout(panConCliente);
        panConCliente.setLayout(panConClienteLayout);
        panConClienteLayout.setHorizontalGroup(
            panConClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panConClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtEmailCliente)
                    .addComponent(rtTelefoneCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panConClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxEmailCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxTelefoneCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        panConClienteLayout.setVerticalGroup(
            panConClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConClienteLayout.createSequentialGroup()
                .addGroup(panConClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtEmailCliente)
                    .addComponent(cxEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panConClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtTelefoneCliente)
                    .addComponent(cxTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        rtSalarioVendedor.setText("Salário:");

        cxSalarioVendedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        rtQtddVendasVendedor.setText("Quantidade de Vendas");

        cxQtddVendasVendedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        javax.swing.GroupLayout panConVendedorLayout = new javax.swing.GroupLayout(panConVendedor);
        panConVendedor.setLayout(panConVendedorLayout);
        panConVendedorLayout.setHorizontalGroup(
            panConVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConVendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panConVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtSalarioVendedor)
                    .addComponent(rtQtddVendasVendedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panConVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxSalarioVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxQtddVendasVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        panConVendedorLayout.setVerticalGroup(
            panConVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConVendedorLayout.createSequentialGroup()
                .addGroup(panConVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtSalarioVendedor)
                    .addComponent(cxSalarioVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panConVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtQtddVendasVendedor)
                    .addComponent(cxQtddVendasVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        cxId.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        rtId.setText("ID:");

        btProcurar.setText("🔍");
        btProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProcurarActionPerformed(evt);
            }
        });

        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panConCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panConVendedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(panConPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btAtualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btExcluir)
                                .addGap(18, 18, 18)
                                .addComponent(btSair)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rtId)
                        .addGap(18, 18, 18)
                        .addComponent(cxId)
                        .addGap(18, 18, 18)
                        .addComponent(btProcurar)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(rtTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(rtTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtId)
                    .addComponent(cxId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btProcurar))
                .addGap(34, 34, 34)
                .addComponent(panConPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panConVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panConCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btAtualizar)
                        .addComponent(btExcluir))
                    .addComponent(btSair))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProcurarActionPerformed
        procurar();
    }//GEN-LAST:event_btProcurarActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        try {
            atualizar();
        } catch (ValorNumericoInvalidoException ex) {
            JOptionPane.showMessageDialog(null, ex.impErro(), "Erro", JOptionPane.OK_OPTION);
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        try {
            excluir();        
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    public JFormattedTextField getCxId() {
        return cxId;
    }
    
    private void atualizarTabelaRelatorio(){
        FormRelPessoa.getInstance().valoresTabela();
    }
    
    private void excluir(){
        int escolha = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir esta pessoa permanentemente? Esta ação não poderá ser desfeita.", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if(escolha==0){
            bd.rmvPessoa(p.getId());
            atualizarTabelaRelatorio();
            limparForm();
            hideForm();
        }
    }
    
    public void procurar(){
        hideForm();
        if(cxId.getValue()!=null){
            p = bd.getPessoa(((Number) cxId.getValue()).intValue());
            if(p!=null){
                panConPessoa.setVisible(true);
                btAtualizar.setVisible(true);
                btExcluir.setVisible(true);
                switch (p.getClass().getName()) {
                    case "Cliente" ->{
                        panConCliente.setVisible(true);
                        rtTitulo.setText("Consulta de Cliente");
                    }
                    default ->{
                        panConVendedor.setVisible(true);                        
                        rtTitulo.setText("Consulta de Vendedor");

                        
                    }
                }
                valores();
            }else{
               JOptionPane.showMessageDialog(null, "O ID inserido é inválido. Por favor, verifique e tente novamente", "Erro de Validação de ID", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Para realizar a pesquisa, é necessário inserir um ID no campo correspondente. Por favor, preencha o campo ID e tente novamente.", "Campo ID Vazio", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void valores(){
        cxNome.setText(p.getNome());
        switch (p.getClass().getName()) {
            case "Cliente" -> {
                Cliente c = (Cliente) p;
                cxEmailCliente.setText(c.getEmail());
                cxTelefoneCliente.setText(c.getTelefone());
            }
            default -> {
                Vendedor v = (Vendedor) p;
                cxSalarioVendedor.setValue(v.getSalario());
                cxQtddVendasVendedor.setValue(v.getQuantidadeVendas());
            }
        }
    }
    
    private void atualizar() throws ValorNumericoInvalidoException{
        if(verificaPreenchimento()){
            switch (p.getClass().getName()) {
                case "Cliente" ->{
                Cliente cliente = (Cliente) p;
                cliente.setEmail(cxEmailCliente.getText());
                cliente.setTelefone(cxTelefoneCliente.getText());    
                }
                default -> {
                Vendedor vendedor = (Vendedor) p;
                vendedor.setQuantidadeVendas(((Number) cxQtddVendasVendedor.getValue()).intValue());
                vendedor.setSalario(((Number) cxSalarioVendedor.getValue()).doubleValue());    
                }
            }
            p.setId(((Number)cxId.getValue()).intValue());
            p.setNome(cxNome.getText());       
            bd.attPessoa(p);
            JOptionPane.showMessageDialog(null,
                    "Os dados da pessoa foram atualizados com sucesso\n"
                    +p.exibirInformacoes(),
                    "Atualização Concluída",
                    JOptionPane.INFORMATION_MESSAGE);
            atualizarTabelaRelatorio();
            limparForm();
            hideForm();
        }else{
            JOptionPane.showMessageDialog(null, "Todos os campos do formulário são obrigatórios. Por favor, preencha-os para continuar.", "Campos Obrigatórios", JOptionPane.OK_OPTION);
        }
    }
    
    private boolean verificaPreenchimento(){
        if(cxNome.getText().isBlank()){
            return false;
        }
        switch (p.getClass().getName()) {
            case "Cliente" -> {
                if(cxEmailCliente.getText().isBlank() || cxTelefoneCliente.getText().isBlank()){
                    System.out.println("Sou cliente");
                    return false;
                }
            }
            default -> {
                if(cxSalarioVendedor.getText().isBlank() || cxQtddVendasVendedor.getText().isBlank()){
                    System.out.println("Sou vende");
                    return false;
                }
            }
        }    
        return true;
    }
    
    private void sair(){
        int escolha = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair da tela de consulta de pessoas?", "Confirmar Saída", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if(escolha==0){
            limparForm();
            this.dispose();            
        }
    }
    
    private void limparForm(){
        cxId.setValue(null);
        cxNome.setText("");
        cxQtddVendasVendedor.setValue(null);
        cxSalarioVendedor.setValue(null);
        cxEmailCliente.setText("");
        cxTelefoneCliente.setText("");
        rtTitulo.setText("Consulta de Pessoas");
    }
    
    public void init(){
        this.setVisible(true);
        this.hideForm();
    }
    
    private void hideForm(){
        panConVendedor.setVisible(false);
        panConCliente.setVisible(false);
        panConPessoa.setVisible(false);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormConPessoa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btProcurar;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxEmailCliente;
    private javax.swing.JFormattedTextField cxId;
    private javax.swing.JTextField cxNome;
    private javax.swing.JFormattedTextField cxQtddVendasVendedor;
    private javax.swing.JFormattedTextField cxSalarioVendedor;
    private javax.swing.JTextField cxTelefoneCliente;
    private javax.swing.JPanel panConCliente;
    private javax.swing.JPanel panConPessoa;
    private javax.swing.JPanel panConVendedor;
    private javax.swing.JLabel rtEmailCliente;
    private javax.swing.JLabel rtId;
    private javax.swing.JLabel rtNome;
    private javax.swing.JLabel rtQtddVendasVendedor;
    private javax.swing.JLabel rtSalarioVendedor;
    private javax.swing.JLabel rtTelefoneCliente;
    private javax.swing.JLabel rtTitulo;
    // End of variables declaration//GEN-END:variables
}
