//Versão 26 NetBeans
//Victor Hugo Concolato Neves - 2576139

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author conco
 */
public class FormPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPrincipal.class.getName());
    
    //Inicio MÉTODO SINGLETON
    private static FormPrincipal principalInstance;
    
    private FormPrincipal() {
        initComponents();
    }
    
    public FormPrincipal getInstance(){
        if(principalInstance==null){
            principalInstance=new FormPrincipal();
        }
        return principalInstance;
    }
    //Fim MÉTODO SINGLETON

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCadVenda = new javax.swing.JButton();
        btRelVenda = new javax.swing.JButton();
        lbTitulo = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cadMovel = new javax.swing.JMenuItem();
        cadPes = new javax.swing.JMenuItem();
        cadVenda = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        consMovel = new javax.swing.JMenuItem();
        consPes = new javax.swing.JMenuItem();
        consVenda = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        relMovel = new javax.swing.JMenuItem();
        relPes = new javax.swing.JMenuItem();
        relVenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btCadVenda.setText("Cadastrar Venda");
        btCadVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadVendaActionPerformed(evt);
            }
        });

        btRelVenda.setText("Relatório Venda");
        btRelVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelVendaActionPerformed(evt);
            }
        });

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTitulo.setText("Sistema de Gerenciamento de Vendas de Móveis");

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jMenu1.setText("Cadastrar");

        cadMovel.setText("Móvel");
        cadMovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadMovelActionPerformed(evt);
            }
        });
        jMenu1.add(cadMovel);

        cadPes.setText("Pessoa");
        cadPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadPesActionPerformed(evt);
            }
        });
        jMenu1.add(cadPes);

        cadVenda.setText("Venda");
        cadVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadVendaActionPerformed(evt);
            }
        });
        jMenu1.add(cadVenda);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultar");

        consMovel.setText("Móvel");
        consMovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consMovelActionPerformed(evt);
            }
        });
        jMenu2.add(consMovel);

        consPes.setText("Pessoa");
        consPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consPesActionPerformed(evt);
            }
        });
        jMenu2.add(consPes);

        consVenda.setText("Venda");
        consVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consVendaActionPerformed(evt);
            }
        });
        jMenu2.add(consVenda);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatório");

        relMovel.setText("Móvel");
        relMovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relMovelActionPerformed(evt);
            }
        });
        jMenu3.add(relMovel);

        relPes.setText("Pessoa");
        relPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relPesActionPerformed(evt);
            }
        });
        jMenu3.add(relPes);

        relVenda.setText("Venda");
        relVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relVendaActionPerformed(evt);
            }
        });
        jMenu3.add(relVenda);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lbTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btCadVenda)
                        .addGap(92, 92, 92)
                        .addComponent(btRelVenda))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(btSair)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lbTitulo)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadVenda)
                    .addComponent(btRelVenda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(btSair)
                .addGap(52, 52, 52))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadMovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadMovelActionPerformed
        FormCadMovel.getInstance().init();
    }//GEN-LAST:event_cadMovelActionPerformed

    private void cadPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadPesActionPerformed
        FormCadPessoa.getInstance().init();
    }//GEN-LAST:event_cadPesActionPerformed

    private void cadVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadVendaActionPerformed
        FormCadVenda.getInstance().init();
    }//GEN-LAST:event_cadVendaActionPerformed

    private void btCadVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadVendaActionPerformed
        FormCadVenda.getInstance().init();
    }//GEN-LAST:event_btCadVendaActionPerformed

    private void consMovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consMovelActionPerformed
        FormConMovel.getInstance().init();
    }//GEN-LAST:event_consMovelActionPerformed

    private void consPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consPesActionPerformed
        FormConPessoa.getInstance().init();
    }//GEN-LAST:event_consPesActionPerformed

    private void consVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consVendaActionPerformed
        FormConVenda.getInstance().init();
    }//GEN-LAST:event_consVendaActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void relMovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relMovelActionPerformed
        FormRelMovel.getInstance().init();
    }//GEN-LAST:event_relMovelActionPerformed

    private void relPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relPesActionPerformed
        FormRelPessoa.getInstance().init();
    }//GEN-LAST:event_relPesActionPerformed

    private void relVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relVendaActionPerformed
        FormRelVenda.getInstance().init();
    }//GEN-LAST:event_relVendaActionPerformed

    private void btRelVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelVendaActionPerformed
        FormRelVenda.getInstance().init();
    }//GEN-LAST:event_btRelVendaActionPerformed
    
    private void sair(){
        int escolha = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair do sistema gerenciador de vendas de móveis?", "Confirmar Saída", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if(escolha==0){
            this.dispose();            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadVenda;
    private javax.swing.JButton btRelVenda;
    private javax.swing.JButton btSair;
    private javax.swing.JMenuItem cadMovel;
    private javax.swing.JMenuItem cadPes;
    private javax.swing.JMenuItem cadVenda;
    private javax.swing.JMenuItem consMovel;
    private javax.swing.JMenuItem consPes;
    private javax.swing.JMenuItem consVenda;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JMenuItem relMovel;
    private javax.swing.JMenuItem relPes;
    private javax.swing.JMenuItem relVenda;
    // End of variables declaration//GEN-END:variables
}
